file=open("tops1.txt","w")
file.write("This is file is now append.")
file.close()
print("File Appended Successfully")
print("*"*50)

file=open("tops1.txt","r")
print(file.read())
file.close()
print("*"*50)

file=open("top1.txt","a")
file.write("\nThis is file is now appended.")
file.close()
print("File Appened Successfully")

file=open("tops2.txt","w+")
file.write("This is w+ mode using python.")
print("Current File Position: ",file.tell())
file.seek(0)
print(file.read())
file.close()
print("W+ Operation Completed")
print("*"*50)
